export const questions = [
    {
      question: 'What is JSX?',
      category: 'React',
      options: [
        'A JavaScript library for building user interfaces',
        'A syntax extension for JavaScript',
        'A method to handle HTTP requests',
        'A way to style components',
      ],
      correctAnswer: 'A syntax extension for JavaScript',
    },
    {
      question: 'What is React?',
      category: 'React',
      options: [
        'A JavaScript library for building user interfaces',
        'A database management system',
        'A server-side language',
        'A game engine',
      ],
      correctAnswer: 'A JavaScript library for building user interfaces',
    },
    {
      question: 'What is ReactDOM?',
      category: 'React',
      options: [
        'To render React components in the DOM',
        'To manage application state',
        'To handle routing',
        'To style components',
      ],
      correctAnswer: 'To render React components in the DOM',
    },
    {
      question: 'Which of the following is a primitive data type in Java?',
      category: 'Java',
      options: [
        'int',
        'String',
        'ArrayList',
        'Object',
      ],
      correctAnswer: 'int',
    },
    {
      question: 'What is the use of the `final` keyword in Java?',
      category: 'Java',
      options: [
        'To define a constant value',
        'To create a new object',
        'To override methods',
        'To handle exceptions',
      ],
      correctAnswer: 'To define a constant value',
    },
    {
      question: 'Which of the following is the correct syntax for defining a function in Python?',
      category: 'Python',
      options: [
        'def functionName()',
        'function functionName()',
        'def: functionName()',
        'function: functionName()',
      ],
      correctAnswer: 'def functionName()',
    },
    {
      question: 'How do you start a loop in Python?',
      category: 'Python',
      options: [
        'for i in range(10):',
        'loop for i in range(10):',
        'for i range(10):',
        'loop for i in 10:',
      ],
      correctAnswer: 'for i in range(10):',
    },
    {
      question: 'What does the `break` statement do in Java?',
      category: 'Java',
      options: [
        'Exits the current loop',
        'Throws an exception',
        'Declares a method',
        'Returns a value from a function',
      ],
      correctAnswer: 'Exits the current loop',
    },
    {
      question: 'Which of the following is used for multiple inheritance in Python?',
      category: 'Python',
      options: [
        'Multiple classes',
        'Class composition',
        'Mixins',
        'Abstract classes',
      ],
      correctAnswer: 'Multiple classes',
    },
    {
      question: 'What is the purpose of `useState` hook in React?',
      category: 'React',
      options: [
        'To manage state in functional components',
        'To perform side effects in functional components',
        'To handle events in components',
        'To create React components',
      ],
      correctAnswer: 'To manage state in functional components',
    },
    {
      question: 'What is a React component?',
      category: 'React',
      options: [
        'A reusable piece of code that defines a part of the UI',
        'A method to handle HTTP requests',
        'A template for creating objects',
        'A function for managing app state',
      ],
      correctAnswer: 'A reusable piece of code that defines a part of the UI',
    },
    {
      question: 'What does the `useEffect` hook do in React?',
      category: 'React',
      options: [
        'Updates the state in functional components',
        'Handles side effects in functional components',
        'Creates a new React component',
        'Manages event listeners in components',
      ],
      correctAnswer: 'Handles side effects in functional components',
    },
    {
      question: 'What is the virtual DOM in React?',
      category: 'React',
      options: [
        'A copy of the browser DOM kept in memory',
        'A library for managing state',
        'A CSS library for styling components',
        'A data format for APIs',
      ],
      correctAnswer: 'A copy of the browser DOM kept in memory',
    },
    {
      question: 'What is `props` in React?',
      category: 'React',
      options: [
        'A way to pass data from parent to child components',
        'A built-in hook to manage state',
        'A method to handle events',
        'A library for routing',
      ],
      correctAnswer: 'A way to pass data from parent to child components',
    },
    {
      question: 'What is the purpose of `React Router`?',
      category: 'React',
      options: [
        'To handle navigation and routing in React applications',
        'To manage application state',
        'To connect to APIs',
        'To handle animations in React',
      ],
      correctAnswer: 'To handle navigation and routing in React applications',
    },
    {
      question: 'What is the default value of a boolean variable in Java?',
      category: 'Java',
      options: [
        'true',
        'false',
        'null',
        '0',
      ],
      correctAnswer: 'false',
    },
    {
      question: 'What is an interface in Java?',
      category: 'Java',
      options: [
        'A blueprint for a class that only contains method declarations',
        'A special type of class used for file handling',
        'A way to manage exceptions',
        'A method for database connectivity',
      ],
      correctAnswer: 'A blueprint for a class that only contains method declarations',
    },
    {
      question: 'What is the purpose of the `super` keyword in Java?',
      category: 'Java',
      options: [
        'To refer to the parent class of the current object',
        'To create a new instance of a class',
        'To define a static method',
        'To stop a thread',
      ],
      correctAnswer: 'To refer to the parent class of the current object',
    },
    {
      question: 'What is the difference between `list` and `tuple` in Python?',
      category: 'Python',
      options: [
        'Lists are mutable, tuples are immutable',
        'Lists are immutable, tuples are mutable',
        'Lists cannot store strings, tuples can',
        'Lists are used for iteration, tuples are not',
      ],
      correctAnswer: 'Lists are mutable, tuples are immutable',
    },
    {
      question: 'What does the `len()` function do in Python?',
      category: 'Python',
      options: [
        'Returns the length of an object',
        'Reverses a list',
        'Converts a string to uppercase',
        'Checks if an object is iterable',
      ],
      correctAnswer: 'Returns the length of an object',
    },
    {
      question: 'What is the purpose of `key` prop in React?',
      category: 'React',
      options: [
        'To uniquely identify elements in a list',
        'To style components',
        'To create a new React component',
        'To manage state',
      ],
      correctAnswer: 'To uniquely identify elements in a list',
    },
    {
      question: 'What is `componentDidMount()` in React?',
      category: 'React',
      options: [
        'A lifecycle method called after a component is rendered',
        'A hook to handle events',
        'A way to declare variables',
        'A method to pass props',
      ],
      correctAnswer: 'A lifecycle method called after a component is rendered',
    },
    {
      question: 'Which method is used to create an object in Java?',
      category: 'Java',
      options: [
        'new',
        'create',
        'init',
        'build',
      ],
      correctAnswer: 'new',
    },
    {
      question: 'What is polymorphism in Java?',
      category: 'Java',
      options: [
        'The ability of an object to take many forms',
        'The inheritance of classes',
        'The declaration of static methods',
        'The process of overloading operators',
      ],
      correctAnswer: 'The ability of an object to take many forms',
    },
    {
      question: 'What is the use of `finally` block in Java?',
      category: 'Java',
      options: [
        'To execute code after try and catch blocks',
        'To handle runtime exceptions',
        'To terminate the program',
        'To declare a final variable',
      ],
      correctAnswer: 'To execute code after try and catch blocks',
    },
    {
      question: 'How do you declare a variable in Python?',
      category: 'Python',
      options: [
        'Using the `=` operator',
        'Using the `var` keyword',
        'Using the `let` keyword',
        'Using the `declare` keyword',
      ],
      correctAnswer: 'Using the `=` operator',
    },
    {
      question: 'What does the `append()` method do in Python?',
      category: 'Python',
      options: [
        'Adds an element to the end of a list',
        'Removes an element from a list',
        'Sorts a list in ascending order',
        'Creates a copy of a list',
      ],
      correctAnswer: 'Adds an element to the end of a list',
    },
    {
      question: 'What is a closure in JavaScript?',
      category: 'JavaScript',
      options: [
        'A function that retains access to its lexical scope',
        'A method to define a class',
        'A way to create objects',
        'A way to loop through arrays',
      ],
      correctAnswer: 'A function that retains access to its lexical scope',
    },
    {
      question: 'What is the purpose of `useRef` in React?',
      category: 'React',
      options: [
        'To access a DOM element directly',
        'To manage state in functional components',
        'To handle routing in React',
        'To perform side effects',
      ],
      correctAnswer: 'To access a DOM element directly',
    },
    {
      question: 'What does the `continue` statement do in Python?',
      category: 'Python',
      options: [
        'Skips the rest of the code in the current iteration of a loop',
        'Exits the current loop',
        'Stops the execution of a function',
        'Starts a new loop',
      ],
      correctAnswer: 'Skips the rest of the code in the current iteration of a loop',
    },
    
  ];
  